apiVersion: apps/v1
kind: Deployment
metadata:
  name: microdonuts
  labels:
    app: microdonuts
spec:
  selector:
    matchLabels:
      app: microdonuts
  template:
      metadata:
        labels:
          app: microdonuts
      spec:
        containers:
          - name: microdonuts
            image: microdonuts:latest
            ports:
              - name: http
                containerPort: 10001
            volumeMounts:
              - name: tracer-config-mnt
                mountPath: /config
        volumes:
          - name: tracer-config-mnt
            configMap: 
              name: tracer-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tracer-config
  labels:
        app: microdonuts
data:
  tracer_config.properties: |
    public_directory=../client

    // Selector for the below config blocks
    tracer=jaeger

    // Jaeger config
    jaeger.reporter_host=jaeger-agent
    jaeger.reporter_port=6831

    // Zipkin config
    zipkin.reporter_host=localhost
    zipkin.reporter_port=9411

    // LightStep config
    lightstep.collector_host=collector.lightstep.com
    lightstep.collector_port=80
    lightstep.access_token={your_token}

---
apiVersion: v1
kind: Service
metadata:
  name: microdonuts
  labels:
    app: microdonuts
spec:
  selector:
    app: microdonuts
  ports:
    - name: website
      targetPort: http
      port: 10001

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: microdonuts
    labels:
        app: microdonuts
spec:
  rules:
    - host: microdonuts.example.com
      http:
        paths:
          - backend:
              serviceName: microdonuts
              servicePort: website

